### Create Song
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "FOLLOW ME 2",
  "artistId": 1
}


### FETCH ALL SONGS
GET http://localhost:3000/songs


### FETCH SONG BY ID
GET http://localhost:3000/songs/3


### UPDATE SONG
PATCH http://localhost:3000/songs/1
Content-Type: application/json

{
  "title": "New Title"
}


### CREATE ARTIST
POST http://localhost:3000/artists
Content-Type: application/json

{
  "title": "Okko",
  "name": "Vondul"
}